#!/bin/sh
pandoc sidebar.md -o sidebar.html
pandoc --template=template.html -B sidebar.html \
       index.md -o index.html
pandoc --template=template.html -B sidebar.html \
       ./call-for-papers/index.md -o ./call-for-papers/index.html
